// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/repo/user.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repo "automation/util/repo"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CountUser mocks base method.
func (m *MockUserRepository) CountUser(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUser", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUser indicates an expected call of CountUser.
func (mr *MockUserRepositoryMockRecorder) CountUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUser", reflect.TypeOf((*MockUserRepository)(nil).CountUser), ctx)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *repo.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// FirstUserByEmail mocks base method.
func (m *MockUserRepository) FirstUserByEmail(ctx context.Context, email string) (*repo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstUserByEmail", ctx, email)
	ret0, _ := ret[0].(*repo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstUserByEmail indicates an expected call of FirstUserByEmail.
func (mr *MockUserRepositoryMockRecorder) FirstUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).FirstUserByEmail), ctx, email)
}

// FirstUserByHashUserID mocks base method.
func (m *MockUserRepository) FirstUserByHashUserID(ctx context.Context, userID string) (*repo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstUserByHashUserID", ctx, userID)
	ret0, _ := ret[0].(*repo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstUserByHashUserID indicates an expected call of FirstUserByHashUserID.
func (mr *MockUserRepositoryMockRecorder) FirstUserByHashUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstUserByHashUserID", reflect.TypeOf((*MockUserRepository)(nil).FirstUserByHashUserID), ctx, userID)
}

// FirstUserByProvider mocks base method.
func (m *MockUserRepository) FirstUserByProvider(ctx context.Context, providerID, provider string) (*repo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstUserByProvider", ctx, providerID, provider)
	ret0, _ := ret[0].(*repo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstUserByProvider indicates an expected call of FirstUserByProvider.
func (mr *MockUserRepositoryMockRecorder) FirstUserByProvider(ctx, providerID, provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstUserByProvider", reflect.TypeOf((*MockUserRepository)(nil).FirstUserByProvider), ctx, providerID, provider)
}

// UpdateUserByProvider mocks base method.
func (m *MockUserRepository) UpdateUserByProvider(ctx context.Context, user *repo.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByProvider", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByProvider indicates an expected call of UpdateUserByProvider.
func (mr *MockUserRepositoryMockRecorder) UpdateUserByProvider(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByProvider", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserByProvider), ctx, user)
}
