// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/repo/session.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	repo "automation/util/repo"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CountActiveUser mocks base method.
func (m *MockSessionRepository) CountActiveUser(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveUser", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveUser indicates an expected call of CountActiveUser.
func (mr *MockSessionRepositoryMockRecorder) CountActiveUser(ctx, cutoff interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveUser", reflect.TypeOf((*MockSessionRepository)(nil).CountActiveUser), ctx, cutoff)
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, session *repo.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, session)
}

// FindByRefreshToken mocks base method.
func (m *MockSessionRepository) FindByRefreshToken(ctx context.Context, refreshToken string) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefreshToken indicates an expected call of FindByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) FindByRefreshToken(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).FindByRefreshToken), ctx, refreshToken)
}

// FirstUser mocks base method.
func (m *MockSessionRepository) FirstUser(ctx context.Context, sessionID string) (*repo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstUser", ctx, sessionID)
	ret0, _ := ret[0].(*repo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstUser indicates an expected call of FirstUser.
func (mr *MockSessionRepositoryMockRecorder) FirstUser(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstUser", reflect.TypeOf((*MockSessionRepository)(nil).FirstUser), ctx, sessionID)
}

// RevokeSessionBySessionID mocks base method.
func (m *MockSessionRepository) RevokeSessionBySessionID(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionBySessionID indicates an expected call of RevokeSessionBySessionID.
func (mr *MockSessionRepositoryMockRecorder) RevokeSessionBySessionID(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionBySessionID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeSessionBySessionID), ctx, sessionID)
}

// RevokeSessionByUserID mocks base method.
func (m *MockSessionRepository) RevokeSessionByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionByUserID indicates an expected call of RevokeSessionByUserID.
func (mr *MockSessionRepositoryMockRecorder) RevokeSessionByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionByUserID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeSessionByUserID), ctx, userID)
}
