// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/provider/x.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	provider "automation/util/provider"

	gomock "go.uber.org/mock/gomock"
)

// MockXOAuth2 is a mock of XOAuth2 interface.
type MockXOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockXOAuth2MockRecorder
}

// MockXOAuth2MockRecorder is the mock recorder for MockXOAuth2.
type MockXOAuth2MockRecorder struct {
	mock *MockXOAuth2
}

// NewMockXOAuth2 creates a new mock instance.
func NewMockXOAuth2(ctrl *gomock.Controller) *MockXOAuth2 {
	mock := &MockXOAuth2{ctrl: ctrl}
	mock.recorder = &MockXOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXOAuth2) EXPECT() *MockXOAuth2MockRecorder {
	return m.recorder
}

// ExchangeToken mocks base method.
func (m *MockXOAuth2) ExchangeToken(ctx context.Context, code, codeVerifier string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, code, codeVerifier)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockXOAuth2MockRecorder) ExchangeToken(ctx, code, codeVerifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockXOAuth2)(nil).ExchangeToken), ctx, code, codeVerifier)
}

// GetProfileFromProvider mocks base method.
func (m *MockXOAuth2) GetProfileFromProvider(ctx context.Context, accessToken string) (*provider.UserProfileFromProviderX, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromProvider", ctx, accessToken)
	ret0, _ := ret[0].(*provider.UserProfileFromProviderX)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromProvider indicates an expected call of GetProfileFromProvider.
func (mr *MockXOAuth2MockRecorder) GetProfileFromProvider(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromProvider", reflect.TypeOf((*MockXOAuth2)(nil).GetProfileFromProvider), ctx, accessToken)
}
