// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/provider/github.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	provider "automation/util/provider"

	gomock "go.uber.org/mock/gomock"
)

// MockGithubOAuth2 is a mock of GithubOAuth2 interface.
type MockGithubOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockGithubOAuth2MockRecorder
}

// MockGithubOAuth2MockRecorder is the mock recorder for MockGithubOAuth2.
type MockGithubOAuth2MockRecorder struct {
	mock *MockGithubOAuth2
}

// NewMockGithubOAuth2 creates a new mock instance.
func NewMockGithubOAuth2(ctrl *gomock.Controller) *MockGithubOAuth2 {
	mock := &MockGithubOAuth2{ctrl: ctrl}
	mock.recorder = &MockGithubOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubOAuth2) EXPECT() *MockGithubOAuth2MockRecorder {
	return m.recorder
}

// ExchangeToken mocks base method.
func (m *MockGithubOAuth2) ExchangeToken(ctx context.Context, code string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, code)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockGithubOAuth2MockRecorder) ExchangeToken(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockGithubOAuth2)(nil).ExchangeToken), ctx, code)
}

// GetProfileFromProvider mocks base method.
func (m *MockGithubOAuth2) GetProfileFromProvider(ctx context.Context, accessToken string) (*provider.UserProfileFromProviderGithub, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromProvider", ctx, accessToken)
	ret0, _ := ret[0].(*provider.UserProfileFromProviderGithub)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromProvider indicates an expected call of GetProfileFromProvider.
func (mr *MockGithubOAuth2MockRecorder) GetProfileFromProvider(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromProvider", reflect.TypeOf((*MockGithubOAuth2)(nil).GetProfileFromProvider), ctx, accessToken)
}
