// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/provider/google.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	provider "automation/util/provider"

	gomock "go.uber.org/mock/gomock"
)

// MockGoogleOAuth2 is a mock of GoogleOAuth2 interface.
type MockGoogleOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleOAuth2MockRecorder
}

// MockGoogleOAuth2MockRecorder is the mock recorder for MockGoogleOAuth2.
type MockGoogleOAuth2MockRecorder struct {
	mock *MockGoogleOAuth2
}

// NewMockGoogleOAuth2 creates a new mock instance.
func NewMockGoogleOAuth2(ctrl *gomock.Controller) *MockGoogleOAuth2 {
	mock := &MockGoogleOAuth2{ctrl: ctrl}
	mock.recorder = &MockGoogleOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleOAuth2) EXPECT() *MockGoogleOAuth2MockRecorder {
	return m.recorder
}

// ExchangeToken mocks base method.
func (m *MockGoogleOAuth2) ExchangeToken(ctx context.Context, code string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, code)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockGoogleOAuth2MockRecorder) ExchangeToken(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockGoogleOAuth2)(nil).ExchangeToken), ctx, code)
}

// GetProfileFromProvider mocks base method.
func (m *MockGoogleOAuth2) GetProfileFromProvider(ctx context.Context, token string) (*provider.UserProfileFromProviderGoogle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromProvider", ctx, token)
	ret0, _ := ret[0].(*provider.UserProfileFromProviderGoogle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromProvider indicates an expected call of GetProfileFromProvider.
func (mr *MockGoogleOAuth2MockRecorder) GetProfileFromProvider(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromProvider", reflect.TypeOf((*MockGoogleOAuth2)(nil).GetProfileFromProvider), ctx, token)
}
