// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/provider/discord.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	provider "automation/util/provider"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscordOAuth2 is a mock of DiscordOAuth2 interface.
type MockDiscordOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordOAuth2MockRecorder
}

// MockDiscordOAuth2MockRecorder is the mock recorder for MockDiscordOAuth2.
type MockDiscordOAuth2MockRecorder struct {
	mock *MockDiscordOAuth2
}

// NewMockDiscordOAuth2 creates a new mock instance.
func NewMockDiscordOAuth2(ctrl *gomock.Controller) *MockDiscordOAuth2 {
	mock := &MockDiscordOAuth2{ctrl: ctrl}
	mock.recorder = &MockDiscordOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordOAuth2) EXPECT() *MockDiscordOAuth2MockRecorder {
	return m.recorder
}

// ExchangeToken mocks base method.
func (m *MockDiscordOAuth2) ExchangeToken(ctx context.Context, code string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, code)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockDiscordOAuth2MockRecorder) ExchangeToken(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockDiscordOAuth2)(nil).ExchangeToken), ctx, code)
}

// GetProfileFromProvider mocks base method.
func (m *MockDiscordOAuth2) GetProfileFromProvider(ctx context.Context, accessToken string) (*provider.UserProfileFromProviderDiscord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromProvider", ctx, accessToken)
	ret0, _ := ret[0].(*provider.UserProfileFromProviderDiscord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromProvider indicates an expected call of GetProfileFromProvider.
func (mr *MockDiscordOAuth2MockRecorder) GetProfileFromProvider(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromProvider", reflect.TypeOf((*MockDiscordOAuth2)(nil).GetProfileFromProvider), ctx, accessToken)
}
