// Code generated by MockGen. DO NOT EDIT.
// Source: ./util/provider/tiktok.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	provider "automation/util/provider"

	gomock "go.uber.org/mock/gomock"
)

// MockTiktokOAuth2 is a mock of TiktokOAuth2 interface.
type MockTiktokOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockTiktokOAuth2MockRecorder
}

// MockTiktokOAuth2MockRecorder is the mock recorder for MockTiktokOAuth2.
type MockTiktokOAuth2MockRecorder struct {
	mock *MockTiktokOAuth2
}

// NewMockTiktokOAuth2 creates a new mock instance.
func NewMockTiktokOAuth2(ctrl *gomock.Controller) *MockTiktokOAuth2 {
	mock := &MockTiktokOAuth2{ctrl: ctrl}
	mock.recorder = &MockTiktokOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTiktokOAuth2) EXPECT() *MockTiktokOAuth2MockRecorder {
	return m.recorder
}

// ExchangeToken mocks base method.
func (m *MockTiktokOAuth2) ExchangeToken(ctx context.Context, code string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, code)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockTiktokOAuth2MockRecorder) ExchangeToken(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockTiktokOAuth2)(nil).ExchangeToken), ctx, code)
}

// GetProfileFromProvider mocks base method.
func (m *MockTiktokOAuth2) GetProfileFromProvider(ctx context.Context, accessToken string) (*provider.UserProfileFromProviderTikTok, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromProvider", ctx, accessToken)
	ret0, _ := ret[0].(*provider.UserProfileFromProviderTikTok)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromProvider indicates an expected call of GetProfileFromProvider.
func (mr *MockTiktokOAuth2MockRecorder) GetProfileFromProvider(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromProvider", reflect.TypeOf((*MockTiktokOAuth2)(nil).GetProfileFromProvider), ctx, accessToken)
}
